Add: Hangar index parameter to ScriptAirport::GetHangarOfAirport
OpenTTD/OpenTTD pull request #12083
Opened 2024-02-13 20:31 UTC by SamuXarick

## Motivation / Problem
ScriptAirport::GetHangarOfAirport is limited to only getting the hangar with index 0 of an airport.

## Description
Add: Hangar index parameter to `ScriptAirport::GetHangarOfAirport`
New parameter accepts the hangar index of the airport.
Compatibility files updated to maintain old behaviour.

## Limitations

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

2024-02-13 20:43 UTC, glx22 commented
Forcing a new parameter which will be 0 for most calls seems annoying.
The function could be modified to allow optional parameter.

2024-02-17 15:41 UTC, glx22 commented
I tried some generic support of optional parameters, but it's way harder than I imagined.
It's still possible to implement it at function level with advanced syntax.

2024-02-18 16:34 UTC, glx22 commented
https://github.com/SamuXarick/OpenTTD/compare/add-extra-parameter-for-AIAicraft-GetHangarOfAirport...glx22:OpenTTD:add-extra-parameter-for-AIAicraft-GetHangarOfAirport is a possible implementation for optional 'index'

2024-02-21 15:46 UTC, SamuXarick commented
> [SamuXarick/OpenTTD@add-extra-parameter-for-AIAicraft-GetHangarOfAirport...glx22:OpenTTD:add-extra-parameter-for-AIAicraft-GetHangarOfAirport](https://github.com/SamuXarick/OpenTTD/compare/add-extra-parameter-for-AIAicraft-GetHangarOfAirport...glx22:OpenTTD:add-extra-parameter-for-AIAicraft-GetHangarOfAirport) is a possible implementation for optional 'index'

I tried with your code, it doesn't seem to work:
![image](https://github.com/OpenTTD/OpenTTD/assets/43006711/cfa219f8-124a-48ee-bfe4-7396efccb2b1)

2024-02-21 18:37 UTC, frosch123 requested changes
This PR is in conflict with #10691.
* This PR wants to expose multiple hangars to scripts.
* #10691 wants to merge all hangars into one, so there will be only one.

2024-02-21 20:31 UTC, SamuXarick commented
> [SamuXarick/OpenTTD@add-extra-parameter-for-AIAicraft-GetHangarOfAirport...glx22:OpenTTD:add-extra-parameter-for-AIAicraft-GetHangarOfAirport](https://github.com/SamuXarick/OpenTTD/compare/add-extra-parameter-for-AIAicraft-GetHangarOfAirport...glx22:OpenTTD:add-extra-parameter-for-AIAicraft-GetHangarOfAirport) is a possible implementation for optional 'index'
Thanks, it's done. Also added Valuate testing optional parameters in the regression and it works!


> This PR is in conflict with #10691.
> 
> * This PR wants to expose multiple hangars to scripts.
> * [Change: Add Depots and DepotIDs for airports with hangars. #10691](https://github.com/OpenTTD/OpenTTD/pull/10691) wants to merge all hangars into one, so there will be only one.

I just combined this PR with that one, created a GS building aircraft on an airport with 2 hangars and it was able to do so on both hangars:
![image](https://github.com/OpenTTD/OpenTTD/assets/43006711/88e82a54-cf11-4904-be17-1675694c4485)

There are no conflicts.

2025-05-14 08:48 UTC, frosch123 commented
The API should not expose any more internals of the airport state machines.
* If we ever get modular/tile-based airports, all these functions are a compatibility hassle.
* None of these functions appear useful to an AI for me. If an AI wants to rank the efficiency of the different airports, it should rather hard-code a list of types.

2025-05-14 08:48 UTC, closed without merging