Add: [Script] GetAirportNumHangars
OpenTTD/OpenTTD pull request #12084
Opened 2024-02-13 21:43 UTC by SamuXarick

## Motivation / Problem
There is no way to get the number of hangars of an airport without having to build it first.

## Description
Add `Script::GetAirportNumHangars` to AI and GS.
This allows to get the number of hangars of a type of airport without having to build it first.

## Limitations
There is `Script::GetNumHangars`, but this method requires the airport to be already built, which is annoying when you're still planning to build one.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

2024-02-14 16:12 UTC, 2TallTyler submitted a review, later dismissed
Make sense to me.

2024-02-14 18:52 UTC, glx22 commented on bin/ai/compat_0.7.nut
> +	return AIAirport.GetAirportNumHangars(AIAirport.GetAirportType(tile));
```suggestion
	local type = AIAirport.GetAirportType(tile);
	if (type == AT_INVALID) return -1;
	return AIAirport.GetAirportNumHangars(type);
```
Something like that would make more sense I think.

2024-02-14 21:19 UTC, PeterN commented
I don't see the point of removing the GetNumHangars() API call. Just simplify it's implementation instead of moving it to Squirrel.

2024-02-21 18:37 UTC, frosch123 requested changes
This PR is in conflict with #10691.
* This PR wants to expose multiple hangars to scripts.
* #10691 wants to merge all hangars into one, so there will be only one.

2024-03-03 10:52 UTC, SamuXarick commented
> This PR is in conflict with #10691.
> 
> * This PR wants to expose multiple hangars to scripts.
> * [Change: Add Depots and DepotIDs for airports with hangars. #10691](https://github.com/OpenTTD/OpenTTD/pull/10691) wants to merge all hangars into one, so there will be only one.

This is not conflicting. See https://github.com/OpenTTD/OpenTTD/pull/10691#issuecomment-1962882428

2025-05-14 08:48 UTC, frosch123 commented
The API should not expose any more internals of the airport state machines.
* If we ever get modular/tile-based airports, all these functions are a compatibility hassle.
* None of these functions appear useful to an AI for me. If an AI wants to rank the efficiency of the different airports, it should rather hard-code a list of types.

2025-05-14 08:48 UTC, closed without merging