Codechange: a .aps is created by MSVC when opening a .rc, so ignore it
OpenTTD/OpenTTD pull request #6706
Opened 2018-04-12 00:34 UTC by glx22

2018-04-12 17:22 UTC, TrueBrain requested changes

2018-04-12 17:22 UTC, TrueBrain commented on .hgignore
> +*.aps
The review already says it :) No newline at end of file :)

2018-04-12 17:23 UTC, TrueBrain commented on .gitignore
> +*.aps
This list is in alphabet; please move this on top of this section

2018-04-12 18:59 UTC, TrueBrain submitted a review, later dismissed

2018-04-13 20:02 UTC, michicc submitted a review, later dismissed

2018-04-14 19:03 UTC, TrueBrain submitted a review, later dismissed

2018-04-14 19:30 UTC, TrueBrain approved these changes

2018-04-14 20:06 UTC, merged