Several improvements in known-bugs file
OpenTTD/OpenTTD pull request #6963
Opened 2018-11-05 17:06 UTC by Greg-21

**In these commits I did the following:**
- changed the order based on the numbering of bugs
- changed "Mac OS X" to "macOS"
- made that lines end closer to the 80th character column
- converted "tabs" to "spaces" (to make sure that every line doesn't much exceed the 80th character column)
- updated the release version
- several other less important changes.

2018-11-05 17:24 UTC, nielsmh commented on known-bugs.txt
> +Long delay between switching songs/music:
This is fixed in master.

2018-11-05 17:24 UTC, nielsmh commented on known-bugs.txt
> +Crashes when playing music [#3941]:
I haven't been able to reproduce crashes with OpenMSX in either of the new music drivers for Windows.

2018-11-05 17:24 UTC, nielsmh commented on known-bugs.txt
> +OpenTTD hangs when started on 32-bit Windows [#4083]:
The DMusic driver was completely rewritten so this should also be fixed now.

2018-11-05 17:24 UTC, nielsmh commented on known-bugs.txt
> +Can't change volume inside OpenTTD [#4416]:
Partially fixed, both Win32 music drivers and the new Fluidsynth driver (for Linux) now support music volume control, and independent of sound effects volume.

2018-11-05 22:55 UTC, Greg-21 commented
@nielsmh Since you are "only" a contributor, I'm not sure that I can trust you. There are more obsolete known bugs, I think, so this is not as important to remove these 4 right now.

A comment from any member about that would be appreciated :)

2018-11-05 23:01 UTC, LordAro commented
Niels literally fixed all those bugs himself...

2018-11-05 23:15 UTC, Greg-21 commented
So the main problem is: if are they fixed, or should be fixed. If "should", better to have more listed bugs.

2018-11-05 23:16 UTC, Greg-21 commented
So the main problem is: if are they fixed, or should be fixed. If "should", better to have more listed bugs, I think.

2018-11-06 15:16 UTC, nielsmh commented
If any items are removed from the list, I'd argue it's better to do that in a separate commit either way. One commit to change formatting, one to change contents.

2018-11-07 08:06 UTC, Greg-21 commented
I think the same as you, so that's why I already have committed them locally and still waiting to push them to remote, because I'd like to know if you are sure you fixed those known bugs, or not, and they just **should** be fixed. If the 2nd scenario, it would be better to have more listed bugs.

2018-11-07 15:06 UTC, nielsmh commented on known-bugs.txt
> +Can't change volume inside OpenTTD [#4416]:
Music drivers that do not support volume control:
- BeOS
- extmidi
Music drivers where volume control might affect both sound effects and music:
- Allegro
Music drivers with fully functioning, independent volume control:
- Win32
- DMusic
- Fluidsynth (new default on Linux)
- Cocoa (macOS)
- QuickTime
- OS/2
- libtimidity (PSP)

2018-11-07 15:14 UTC, nielsmh commented
There are no known bugs or glitches in the new Win32 and DMusic music drivers.

I haven't rigorously tested the new Fluidsynth driver, but seeing the code is very simple, any bugs are likely to be in the underlying Fluidsynth library and not OpenTTD's usage of it. I left it playing OpenMSX and other music sets on its own for a good while and didn't notice any oddities.

(It's possible to trigger some shutdown-related race conditions causing assertion errors in the Win32 music driver, when running OpenTTD under a debugger and using breakpoints that trigger during shutdown, but I haven't been able to reproduce those with a release build running outside a debugger.)

2018-11-07 16:17 UTC, Greg-21 commented
Your certainty convinced me :D I just pushed the commit.

2018-11-24 23:28 UTC, michicc requested changes

2018-11-24 23:28 UTC, michicc commented on known-bugs.txt
> +bug tracking system at https://github.com/OpenTTD/OpenTTD/issues.
Singular small nit-pick: Somebody _will_ copy the URL with the dot included and GitHub is unfortunately returning a 404 for it. As such, the old format is preferred.

2018-11-27 19:32 UTC, michicc approved these changes

2018-11-27 19:35 UTC, Greg-21 commented on known-bugs.txt
> +bug tracking system at https://github.com/OpenTTD/OpenTTD/issues.
Good point :) I removed that dot.

2018-11-27 19:55 UTC, merged