Town name filtering
OpenTTD/OpenTTD pull request #6983
Opened 2018-11-27 11:52 UTC by telk5093

It's my first OpenTTD PR, and please let you know I'm very **new to c++ and openttd's codes.**
I mend this code invisibliy and it works very strangely.
So please advice your enhanced code, and you can ignore/edit this commit.

This allows filtering town names like below:
![image](https://user-images.githubusercontent.com/10726524/49080163-16fcb600-f286-11e8-8e1a-786b08da4d69.png)

2018-11-27 15:25 UTC, nielsmh reviewed
Thanks for your contribution! Overall it looks good, there's a few things you should change, mostly cosmetic.

You also need to change the commit message to follow the scheme used, always starting with a keyword (like Add, Change, Fix), a colon, and then the message. Do this with a commit amend in Git, and force-push your branch. (Amending and force-pushing is often frowned upon, but necessary in this case. Github handles it correctly and updates the PR.)

2018-11-27 15:25 UTC, nielsmh commented on src/widgets/town_widget.h
> +	WID_SL_FILTER,           ///< Filter of name.
Wrong identifier name, make sure it's unique for each window. `WID_TD_FILTER` instead.

2018-11-27 15:25 UTC, nielsmh commented on src/town_gui.cpp
> +						SetDataTip(STR_LIST_FILTER_OSKTITLE, STR_LIST_FILTER_TOOLTIP),
Breaking the line here doesn't really match the surrounding code. For the most part we don't break long lines, unless it really improves readability.

2018-11-27 15:25 UTC, nielsmh commented on src/town_gui.cpp
> +	SmallVector<bool, 32> town_items_shown; ///< Map of the filtered out town names
You should align the comments here, so they all start on the same column.

2018-11-27 15:25 UTC, nielsmh commented on src/town_gui.cpp
> +		char buf[64];
Magical number, I think this should be `MAX_LENGTH_TOWN_NAME_CHARS` instead.

2018-11-28 15:18 UTC, telk5093 commented
@nielsmh Thanks for your kind comments. I've corrected, is it okay?

2018-11-29 20:52 UTC, nielsmh commented
I don't have anything more for now. Will find time to test it later :)

2019-01-01 22:09 UTC, J0anJosep commented
Thanks for the PR.
Each time a new widget is added, run /src/script/api/generate_widget.sh and add the modified lines into your commit.

2019-01-02 15:58 UTC, telk5093 commented
@J0anJosep Thanks for your notice, I committed, is it right?

2019-01-02 16:35 UTC, LordAro commented
You'll want to rebase & force-push to merge the commits together, but that's the right idea

2019-01-02 17:43 UTC, planetmaker commented
It looks nice. However the sorting doesn't seem to be stable even when I do not change input into the search box (anymore). The resulting list flickers and changes order randomly for me. That doesn't happen with the full list where the entries immediately follow eachother.

I currently can only speculate as to the reasons: I assume a sub-list is generated from the whole list - and display sometimes happens before sorting, but after generation of the sub-list - but most times it happens correctly after sub-list generation and its sorting.

2019-01-05 16:05 UTC, LordAro requested changes
As per @planetmaker's comments

2019-01-06 20:03 UTC, telk5093 commented
@planetmaker Thanks for your comment, even though I cannot understand 100% what you're meant to because of my lack of english/coding skills.
I'll try to rewrite my code. (of course I think it will take a long time ;p)

2019-01-06 20:03 UTC, closed without merging