Change: use vcpkg integration in Visual Studio
OpenTTD/OpenTTD pull request #6989
Opened 2018-12-25 00:58 UTC by glx22

Removes the need for us to provide OpenTTD-useful package

2018-12-25 09:13 UTC, TrueBrain requested changes
Sweet :D

Please also update https://github.com/OpenTTD/OpenTTD/blob/master/README.md#70-compiling with the new instructions in the Pull Request. Otherwise a lot of people will be a bit confused :)

2018-12-25 09:14 UTC, TrueBrain commented on src/stdafx.h
> +#	if defined(WITH_ZLIB)
Possibly a comment to indicate why this is needed?

2018-12-25 23:48 UTC, glx22 commented
https://github.com/OpenTTD/OpenTTD/blob/master/docs/Readme_Windows_MSVC.txt will need an update too, but it's a lot bigger than the scope of this PR (and I'm not good at documentation)

2018-12-26 08:42 UTC, TrueBrain requested changes
Sorry, I disagree; it is not bigger than the scope of this PR to make that file at least factual correct (or at least for the parts references in this PR). Even if you are not good at documentation, doing what you did for README.md is always the least we can do :) If we don't fix things like that, we make it a lot harder for new people, which is counterproductive :)

2018-12-26 09:13 UTC, TrueBrain commented
Added the documentation (and this PR) as part of #6991. Let's continue there :)

2018-12-26 09:13 UTC, closed without merging