Add: generate_widget.vbs to allow script_window.hpp enums generation …
OpenTTD/OpenTTD pull request #7022
Opened 2019-01-06 15:50 UTC by glx22

…for users unable to run bash/gawk scripts

2019-01-20 19:29 UTC, nielsmh requested changes
I ran `generate_widget.vbs` and it deleted everything in `script_window.hpp`.

2019-01-20 20:05 UTC, nielsmh commented
Turns out the issue is that the VBScript version doesn't handle Unix line endings at all. If the input file has `\n` only for line endings, the file is considered a single line, and just cleared out.

Either the VBScript should handle both types of line endings, or it should at least abort if the file doesn't seem to use DOS-style.

2019-01-20 20:38 UTC, glx22 commented
It now falls back to \n if \r\n fails

2019-01-23 18:33 UTC, nielsmh approved these changes

2019-01-23 18:44 UTC, merged