6599
OpenTTD/OpenTTD pull request #7049
Opened 2019-01-12 21:07 UTC by Eddi-z

2019-01-12 21:16 UTC, andythenorth commented
Tested, solves the issues described in #6599

2019-01-13 22:25 UTC, LordAro requested changes
Can't see anything wrong with the code
Can I be annoying and ask you to capitalise the commit messages properly? (and also fix typos) :>

2019-01-13 22:25 UTC, LordAro commented on src/build_vehicle_gui.cpp
> +			case VEH_AIRCRAFT: if (!w->IsListViewMode() && !CanVehicleUseStation(*eid, Station::GetByTile(w->window_number))) return false; break;
I feel this case is weird enough that the case bodies should be aligned properly, instead of being on one line. Also default at the end

2019-01-27 19:20 UTC, Eddi-z commented on src/build_vehicle_gui.cpp
I'm not entirely sure what this change is doing here

2019-01-28 19:41 UTC, nielsmh requested changes
The first two changes seem fine, but the remaining four codechanges are fishy and seem to make changes then undo/rework them right afterwards. Can we get just the functional/bugfixing patches in alone, then look at the code quality ones separately?

2019-02-03 07:43 UTC, PeterN commented
In #6599, this is a problem.
> I have something for this, and more.
The sortlist changes might be okay but they're nothing to do with disabling the Buy button.

2019-02-22 21:12 UTC, PeterN commented
Already fixed by #7217

2019-02-22 21:12 UTC, closed without merging