Feature: Moveable depots #6328
OpenTTD/OpenTTD pull request #7051
Opened 2019-01-12 22:31 UTC by Eddi-z

patch imported from flyspray
minor conflict resolved
savegame bump rebased (TODO: put correct version info)
patch queue seems "unclean" (partial patch did not compile, whole queue does)

2019-01-12 22:43 UTC, andythenorth commented
Gave this 5 minutes of testing, initial impressions are that all worked as expected.  It's pretty neat.

FWIW, adf88 considered there was more to do on the original patch https://github.com/OpenTTD/OpenTTD/issues/6328#issuecomment-379454447 

However it might be useful as is.

2019-01-12 23:01 UTC, andythenorth commented
From CI: 2019-01-12T22:39:23.2400344Z Running ai/regression/tst_regression... failed!

2019-01-13 00:22 UTC, glx22 commented
First regression error is at main.nut:1062, it's because the rail depot list is empty but it shouldn't as a rail depot as been built. 

Second regression error is at main.nut:1167, it's because the road depot list actually contains the water depot list.

2019-01-13 00:28 UTC, glx22 commented on src/script/api/script_depotlist.cpp
> +		if (depot->IsInUse() && (depot->owner == ScriptObject::GetCompany() || ScriptObject::GetCompany() == OWNER_DEITY) && depot->type == (int)tile_type) this->AddItem(depot->xy);
Regression fails here

2019-01-13 00:39 UTC, glx22 commented on src/script/api/script_depotlist.cpp
> +		if (depot->IsInUse() && (depot->owner == ScriptObject::GetCompany() || ScriptObject::GetCompany() == OWNER_DEITY) && depot->type == (int)tile_type) this->AddItem(depot->xy);
Easy to fix, tile_type should be transport_type

2019-02-05 10:28 UTC, Eddi-z commented on src/order_cmd.cpp
>  				} else {
i'm not 100% sure i correctly resolved conflicts with 3e0e3cfac1 and 81330b8d6e here

2019-03-21 08:34 UTC, PeterN commented
@Eddi-z will you update this?

2019-03-21 17:19 UTC, Eddi-z commented
So, i resolved the saveload part, but the viewport part is way over my head with the kdtree changes.

2019-04-04 16:05 UTC, nielsmh commented
I rebased this branch and updated it to use Kdtree here: https://github.com/nielsmh/OpenTTD/tree/movable-depots
Since I rebased I can't make a PR, and I don't want to push to Eddi's branch without an ok first.

2019-04-07 16:12 UTC, PeterN requested changes

2019-04-07 16:12 UTC, PeterN commented on src/depot.cpp
> +			v->dest_tile = v->GetOrderDepotLocation(this->index);
Use `v->SetDestTile()` so any caches are cleared.

2019-04-07 16:12 UTC, PeterN commented on src/depot_cmd.cpp
> +		if ((_tick_counter + d->index) % DEPOT_REMOVAL_TICKS == 0) {
Duff this up to reduce indentation? `if (... != 0) continue;`

2019-04-08 22:41 UTC, PeterN commented
Found a crash:
1. Build a depot
2. Build an engine
3. Sell the engine
4. Bulldoze the depot
5. Profit?

Something to do with Order backups...

2019-08-17 20:52 UTC, LordAro commented
Hi, there's been no activity on this for over 4 months. If no more effort will be put into this PR, it will be closed in the next week or so

2019-10-22 20:45 UTC, andythenorth commented
I think we can let this one slide into the darkness.  Moving depots is a nice feature if you use escape depots or similar, but it's not essential.

2019-10-22 20:45 UTC, closed without merging