Add: smart town name first steps - #7037
OpenTTD/OpenTTD pull request #7068
Opened 2019-01-17 05:27 UTC by nikolas

This adds structure for some basic town naming rules based on location.

When towns are generated, a mask is read for the random name, to see if
it's a suitable name for this town tile. Currently it just prevents
towns from being named with "Puerto" or "havn" if they're not near the
water, and will only do anything on Latin-American, Danish, or Norwegian
town names.

2019-01-31 14:30 UTC, planetmaker requested changes
I like the idea a lot to choose town names more sensibly wrt location on the map.

However I do not like the idea to go by actual string matching as it is tied to specific strings. There's a LOT of townname NewGRFs out there who could profit from an approach which gives them the same info  - or alternatively allows them to provide flags for like "near sea| near river | on mountain | between mountains | near woods | in desert" or similar.

My suggestion as such is to modify the string lists that each string can be accompanied by flags which makes them either favour or avoid certain conditions - and use those flags to decide applicability of the name to a location (maybe introduce one flag 'not generic' which indicates special location recommendation for a name - 'not generic' so that a list without anything set will treat anything as generic name)

2019-02-10 18:00 UTC, LordAro commented
It's an interesting concept, but I think it's far too early in development to be worth PRing. By all means reopen/make a new PR if you progress with it

2019-02-10 18:00 UTC, closed without merging

2019-02-10 18:07 UTC, nikolas commented
Cool.. yea i was going to close this PR but wasn't sure if it was better to keep the conversation here. But yeah, I'll open a new PR if I move forward with this implementing some sort of flag system to not make this string-based.

2019-02-10 19:30 UTC, planetmaker commented
It's good to keep the conversation (but even closed it's not gone) You can also re-open this one