Update: Changelog
OpenTTD/OpenTTD pull request #7170
Opened 2019-02-03 16:40 UTC by LordAro

I imagine the changelog list needs some work

Other files:
* README.md - no date
* known-bugs.txt - already updated
* installer.nsi - already pointing at 1.9.0-beta1, will be updated after beta release
* AI/GS changelogs, rev.cpp.in - not until actual release

2019-02-03 16:47 UTC, glx22 commented on changelog.txt
> +- Fix #6636: Airplanes could be sent toto helicopter station depots
toto ;)

2019-02-07 20:37 UTC, nielsmh submitted a review, later dismissed
Looks good to me.

2019-02-07 20:40 UTC, nikolas commented on changelog.txt
> +- Fix #6584: Text layout in engine preview dialogue windows was
Incomplete sentence here: I would just remove "windows was" at the end, so it just reads "Fix #6584: Text layout in engine preview dialogue"

2019-02-09 12:28 UTC, TrueBrain approved these changes
Approving because @nielsmh  already did :D

2019-02-09 14:16 UTC, frosch123 commented on changelog.txt
> +- Fix: [NewGRF] Variable 0x85 had no bounds checks
- Fix: [NewGRF] Action7 variable 0x85 had no bounds checks

2019-02-09 14:16 UTC, TrueBrain requested changes
I take that back :P

Please also update `known-bugs.txt` for 1.9.0-beta1 (I think?)
Please update the date to today
Please look at your commit message :)

Tnx!

2019-02-09 14:39 UTC, TrueBrain approved these changes

2019-02-09 14:47 UTC, merged