Change: making the style of MakeVoid calls uniform
OpenTTD/OpenTTD pull request #7192
Opened 2019-02-07 18:32 UTC by Gabda87

Started form making "sizex * y + x" into TileXY(x, y).

2019-02-07 20:14 UTC, LordAro requested changes
Good in principle, though I'm not a fan of the `const uint maxX/Y` additions. No point making a constant that's only used in one place. Probably not worth it for the other places either - any half decent compiler will optimise them out (is the function itself marked inline?)

I'd recommend looking for other potential uses of `TileXY` as well, I have no doubt there are many others

Oh, and the commit should be `Codechange: ...` when no user visible changes are made

2019-02-07 20:41 UTC, Gabda87 commented
@LordAro: Can you have a look at the first version, [`87eacea`](/OpenTTD/OpenTTD/commit/87eacea68892160089da9fe95fa9103ee9446307)? That was without the extra variables.
I'll change the commit message.

2019-02-08 23:04 UTC, LordAro approved these changes

2019-02-08 23:04 UTC, LordAro commented on src/tgp.cpp
> -		for (int x = 0; x < _height_map.size_x;     x++) MakeVoid(x);
seems to me like _height_map could go away entirely, but that's for another time :)

2019-02-08 23:05 UTC, merged