Codechange: Sprite sorting optimization
OpenTTD/OpenTTD pull request #7484
Opened 2019-04-07 08:22 UTC by jmakovicka

Another take on the sprite sorter optimization.

On top of the reverted 25ab9c1997f770f4a8a66bb3ad4b82ba87e3a977 ,
this patch adds the psdMax variable tracking the start of the
still intact pre-sorted portion of the parent sprite vector,
where the early bailout logic still works.

2019-04-07 08:23 UTC, jmakovicka commented
This version of the 4k unzoom fix should avoid the splite flickering caused by wrong sort order with the previous attempt, while maintaining the performance improvement.

2019-04-07 11:24 UTC, michicc commented on src/viewport.cpp
> +	QSortT(psdv->data(), psdv->size(), CompareParentSprites);
We are trying to move to something closer to modern C++, thus something with `std::sort` would be preferable.

2019-04-07 15:03 UTC, PeterN requested changes

2019-04-07 15:03 UTC, PeterN commented on src/viewport.cpp
> +					}
Can be simplified to:
`if (psd2 > psdMax) break;`
`continue;`

2019-04-07 15:03 UTC, PeterN commented on src/viewport.cpp
> +				psdMax = psd2;
OpenTTD-style is single-line or use brackets. This is fine here:
`if (psd2 > psdMax) psdMax = psd2;`

2019-04-07 15:03 UTC, PeterN commented on src/viewport_sprite_sorter_sse4.cpp
> +				}
Same as in viewport.cpp

2019-04-07 15:03 UTC, PeterN commented on src/viewport_sprite_sorter_sse4.cpp
> +				psdMax = psd2;
Same

2019-04-08 17:28 UTC, PeterN commented
This is still broken with regards to sorting, e.g. FIRS industry set.

2019-04-08 19:49 UTC, jmakovicka commented
This is weird. This time, I used https://github.com/jmakovicka/OpenTTD/commit/c96cc5a973c1f01638e1b94c9fedb20e38947b6f to test that the two versions give the same result, at least if the original is suipplied with the same pre-sorted input, as the exact sort result is input dependent.

2019-04-08 22:30 UTC, PeterN commented
The pre-sorting in your regression test messes up the sorting for the current sorter as well.

2019-04-09 19:14 UTC, michicc commented
Without having actually checked anything: Should this maybe use a stable sort (i.e. `std::stable_sort`)?

2019-05-16 21:27 UTC, closed without merging