Add: UDP query of game script
OpenTTD/OpenTTD pull request #7771
Opened 2019-10-15 09:58 UTC by TheDude-gh

Reopened from old flyspray issue #6211.

Patch adds a possibility to query OpenTTD server for running game scripts and returns its name and version if any present.

Goal of this fork is to also create ingame interface.

2019-10-17 19:35 UTC, LordAro requested changes
Just codestyle issues, nothing major

2019-10-17 19:35 UTC, LordAro commented on src/network/core/udp.cpp
> +void NetworkUDPSocketHandler::Receive_SERVER_GAMESCRIPT(Packet *p, NetworkAddress *client_addr) { this->ReceiveInvalidPacket(PACKET_UDP_SERVER_GAMESCRIPT , client_addr); }
extra space before ','

2019-10-17 19:35 UTC, LordAro commented on src/network/core/udp.h
> +	PACKET_UDP_CLIENT_GET_GAMESCRIPT,///< Requests the name of a game script
needs a space separator, or the whole thing needs realigning

2019-10-17 19:35 UTC, LordAro commented on src/network/network_udp.cpp
> +	else{
various codestyle issues with the if here

2019-10-17 19:35 UTC, LordAro commented on src/network/network_udp.cpp
> +	uint8 num_gs;
No need to predeclare the variable, just on-use will be fine

2019-10-17 19:35 UTC, LordAro commented on src/network/network_udp.cpp
> +  void Receive_SERVER_GAMESCRIPT(Packet *p, NetworkAddress *client_addr) override;
not tab indented (this is why the commit checker is failing)

2020-12-14 14:23 UTC, TrueBrain commented
Three things worth mentioning:

1) I think if we do this, we should add more metadata about the game, not only the name of the gamescript. Like AIs running, km of road put down, etc.
2) There is already a packet that sends basic information about the server. I am not sure that adding a new packet with just this content is worth it. If we would be to use it, we would query every server twice: once for the generic info, once for this info (or three times if you run NewGRFs). That sounds like the wrong approach. This needs more consideration from a server perspective.
3) Given the author has not picked up the requested code-changes, I am going to assume there is no longer any interest in adding this function. If there is, please do open up the Pull Request again, and we can talk further :)

2020-12-14 14:23 UTC, closed without merging