Fix #7631: replace produced&transported with cargo sprites in industry directory
OpenTTD/OpenTTD pull request #7809
Opened 2019-10-28 23:45 UTC by glx22

![industry_directory](https://user-images.githubusercontent.com/2952192/67726023-c4bb9c00-f9e4-11e9-88dd-81a125b56d1d.png)

It's just a basic change. The window may need to be rewritten.
English.txt needs to be cleaned up

2019-10-29 01:24 UTC, James103 commented
Would it be possible to implement one of the following systems instead of just going to cargo sprites and hiding a bunch of information from players? This will retain more information in the industry directory window.

Plan A:
1-4 cargoes: Display the full cargo produced and transported ("100 tons of coal (50% transported)")
5-9 cargoes: Display only the cargo produced and the amount ("100 tons of coal, 200 tons of iron")
10+ cargoes: Display only the name of the cargo produced ("Coal, Iron, Gold, and Diamonds")

Plan B:
Cargoes 1-4: Display the full info regarding cargo produced and transported
Cargoes 5+: Collapse with a "...", "etc.", or "and more". Open industry window to view all cargoes there.
Example: "100 tons of coal, 200 tons of iron, 300 tons of gold, 400 tons of diamonds, and more"

2019-10-29 06:34 UTC, ldpl commented
But why? IMO this change make industry window completely pointless as amount of produced cargo was the only useful info there. Also default cargo icons are terrible in this context. They're too small and not very recognizable.

2019-10-29 07:15 UTC, LordAro commented
Why? Because currently the window hard crashes if your industry has more than 7 cargos produced/accepted.

I do agree that this isn't the correct solution though...

2019-11-02 17:10 UTC, andythenorth commented
Could we do this:

* sort cargos by amount produced, highest > lowest
* take the first n (up to the limit of string params)
* append 'and x more...'

??

2019-11-03 02:19 UTC, glx22 commented
So something like ![Unnamed, 15th Jan 1950](https://user-images.githubusercontent.com/2952192/68079346-865d1d00-fde8-11e9-8c3a-b8d8c39dbc35.png) would be preferred.

2019-11-03 10:02 UTC, andythenorth commented
Given that we have a hard-crash currently, I think that looks like a pretty good fix 👍 

Long-term, maybe we should change string handling so we can show all the cargos, but that also raises UI questions (horizontal overflow).  Let's fix the immediate crash.

2019-11-03 16:45 UTC, michicc submitted a review, later dismissed

2019-11-03 21:45 UTC, LordAro requested changes

2019-11-03 21:45 UTC, LordAro commented on src/industry_gui.cpp
> +		struct Cargo {
inline struct, that's a bit bold :)
"Cargo" is a bit generically named, are there no name conflicts/shadowing going on?

2019-11-03 21:45 UTC, LordAro commented on src/industry_gui.cpp
> +			bool operator< (const Cargo &other) const
this function appears to actually be implementing `>`... Confusing at best, incorrect at worst? Perhaps implement `>` (or `>=`) then define `<` in terms of that?

2019-11-04 11:41 UTC, glx22 commented
Oups I should have checked with mingw before pushing

2019-11-04 21:39 UTC, Eric-01 commented
While you are on it, what do you think about connecting your first presented idea with the existing one? To be more precise, I mean adding a cargo icon in front of each "x tonnes of y (z% transported)" string in both the corporate Industries window and all own windows of industries.

I think this shouldn't be hard to implement, and it could help you find the cargo type you're looking for, without the need to read each description.

2019-11-10 19:04 UTC, LordAro approved these changes

2019-11-13 08:11 UTC, merged