Fix: Ensure a minimum gap of water upon generating terrain with original generator
OpenTTD/OpenTTD pull request #7883
Opened 2019-12-29 18:20 UTC by SamuXarick

- When freeform_edges was on, NE and NW borders could have terrain adjacent to the void tiles
- SE and SW borders minimum gap was 2-tile wide instead of 1

2020-04-13 16:05 UTC, LordAro submitted a review, later dismissed
Probably fine.

2020-09-24 17:36 UTC, LordAro submitted a review, later dismissed
Sure.

2020-12-15 19:18 UTC, TrueBrain requested changes
I fixed the issues locally; will push it in a sec. Wanted to leave the feedback behind for posterity.

2020-12-15 19:18 UTC, TrueBrain commented on src/landscape.cpp
> +	if (y < (uint)2 + (_settings_game.construction.freeform_edges ? 1 : 0)) return;
`freeform_edges` doesn't exist for the original generator, so this is confusing (and wrong I think?)

2020-12-15 19:18 UTC, TrueBrain commented on src/landscape.cpp
> +	if (y + h >= MapMaxY()) return;
And here you don't account for `freeform_edges`?

2020-12-15 19:28 UTC, TrueBrain commented on src/landscape.cpp
> +	if (y < (uint)2 + (_settings_game.construction.freeform_edges ? 1 : 0)) return;
Owh, it does, so this is correct; but that still makes me unclear why it wouldn't be needed on the other side of the map ;)

2020-12-15 19:41 UTC, TrueBrain commented
Ah, figured it. `freeform_edges` only sets x=0 and y=0 to VOID. That explains.

Reworked the patch a bit to have less lines. Will merge later :)

2020-12-15 19:42 UTC, TrueBrain approved these changes, later dismissed

2020-12-15 19:43 UTC, frosch123 commented
I think this is wrong.
With fixed edges there is supposed to be a border with flat water tiles.
While with freeform edges also the border can be sloped.

2020-12-15 19:45 UTC, TrueBrain commented
Nothing changed there, it can still be sloped.

What this changes, is what the generator outputs. It used to be that with 2 borders it should be sloped, but the other two always had 2 tiles of water, during generation. That just looks odd.

The only real choice here is, I guess, if it should generate sloped borders; if so, it should do that in all 4 borders ;) But that really does look ugly :)

2020-12-15 19:58 UTC, TrueBrain approved these changes

2020-12-15 20:52 UTC, merged