Directory list window sort perf improvements
OpenTTD/OpenTTD pull request #7914
Opened 2020-01-07 00:17 UTC by JGRennison

Avoid unnecessary resorts of the town and industry directory windows due to population and production changes respectively, when the current sort mode does not depend on the town population or industry production.

Avoid regenerating town, station and industry name strings on every sort comparison and on every town name filter.
Measurements of the time taken to sort the town directory window on a 4k x 4k map indicated a reduction in sort time of between 7.5x and 11x.

2020-01-07 00:51 UTC, glx22 commented on src/industry_gui.cpp
> +			case IDIWD_FORCE_RESORT:
could be `default:`

2020-01-07 07:58 UTC, nielsmh reviewed
Overall, yes please :)

2020-01-07 07:58 UTC, nielsmh commented on src/base_station_base.h
> +	private:
Indentation level

2020-01-07 07:58 UTC, nielsmh commented on src/town.h
> +	private:
Indentation

2020-01-07 07:58 UTC, nielsmh commented on src/base_station_base.h
> +	std::unique_ptr<const char, FreeDeleter> cached_name; ///< NOSAVE: Cache of the resolved name of the station, if not using a custom name
Could just as well use a std::string?

2020-01-07 07:58 UTC, nielsmh commented on src/town.h
> +	std::unique_ptr<const char, FreeDeleter> cached_name; ///< NOSAVE: Cache of the resolved name of the town, if not using a custom town name
std::string?

2020-01-07 09:07 UTC, LordAro commented on src/base_station_base.h
> +		if (!this->cached_name) const_cast<BaseStation *>(this)->FillCachedName();
would marking `cached_name` as mutable remove the need for this cast?

2020-01-08 21:34 UTC, LordAro approved these changes
LGTM

2020-01-08 21:40 UTC, LordAro requested changes

2020-01-08 21:40 UTC, LordAro commented on src/base_station_base.h
> +#include <memory>
Neither of these are required any longer, I think

2020-01-10 21:21 UTC, LordAro approved these changes

2020-01-12 19:37 UTC, merged