Feature: Double-click to rename vehicle
OpenTTD/OpenTTD pull request #8008
Opened 2020-02-18 16:18 UTC by kiwitreekor

2020-02-18 16:36 UTC, ldpl commented
It's not complicated already, same two clicks, just with some mouse movement in between. Perfectly ok for not so widely used function IMO. Totally not worth adding another obscure interface quirk that 99% of players won't even know about. Also, double click will probably bring even more suffer and despair to touchscreen ports UI.

2020-02-18 17:42 UTC, kiwitreekor commented
As far as I know, pretty many people use this function, and I think clicking on its name to rename vehicle is intuitive enough.

2020-02-22 14:36 UTC, LordAro requested changes
I don't have any issue with this in principle...

2020-02-22 14:36 UTC, LordAro commented on src/vehicle_gui.cpp
> +			case WID_VV_CAPTION: { // rename
No need for braces here

2020-02-22 14:36 UTC, LordAro commented on src/vehicle_gui.cpp
> +	void OnQueryTextFinished(char* str) override
```suggestion
	void OnQueryTextFinished(char *str) override
```

2020-02-22 18:13 UTC, telk5093 commented
It would be great if we can add a configuration for this, if you don't want to increase the number of configurations.

2020-02-22 18:58 UTC, kiwitreekor commented
@telk5093 Now I added option to enable/disable it.

2020-02-22 19:01 UTC, LordAro commented
I don't agree with having a setting here. This isn't something that visibly changes the behaviour/look of the game. If you don't want to double-click... don't

2020-02-22 19:11 UTC, kiwitreekor commented
@LordAro hmm... now reverted to original version.

2020-02-27 21:36 UTC, SamuXarick commented
I could double click on a competitor road vehicle and try rename it, only to get an error saying it's not mine.

2020-04-15 09:58 UTC, James103 commented
Somehow the OpenTTD CI broke on this pull request. One of the checks is saying "Expected" for months, the OpenTTD CI logs aren't found, but the Commit checker logs are still accessible. Maybe try running the checks again?

2020-04-25 09:36 UTC, kiwitreekor commented
> I could double click on a competitor road vehicle and try rename it, only to get an error saying it's not mine.
> 
> The tooltip doesn't mention anything about double-click to rename, only to drag.

Fixed

2020-05-28 04:52 UTC, techgeeknz commented
Currently, renaming things can be a pain. Would we be better served by placing a small “edit” icon next to re-nameable items? In instances where this name appears as the title of a window, the title bar seems like a perfectly logical place for such an icon.

2020-12-13 14:34 UTC, frosch123 commented
To add my opinion to the pile:
* I would expect double-click to maximize/minimize/share the window.
* For renaming i would expect some small button in the titlebar, that behaves the same for vehicles, stations, companies, and everything you can rename.
* There was a similar dicussion about adding "scroll to" buttons to all windows that represent some entitiy with a location on the map.

2020-12-14 15:13 UTC, TrueBrain commented
Many people have different expectations of their UI, depending on what they are used to in their day-to-day. OpenTTD's UI dates to, what, 1994, and wasn't aware of the many common concepts we have today. In result, it is a mixed bag of everything that was and was becoming. In short: the UI sucks :P

That said, I can fully understand that functionalities like this help some people, but that it frustrates the hell out of others. This needs a more generic fix, for example with presets or what-ever, to allow patches like this.

To not poke the bear too much, sadly, I think we should close this PR for now. I do not expect that we come to a consensus about it any time soon, and allowing any form of presets (or themes, or how-ever you want to call it) will take a while.

I am really sorry, as I personally like it :D

2020-12-14 15:13 UTC, closed without merging