Fix: [AI/GS] AreWaterTilesConnected wasn't handling aqueducts properly
OpenTTD/OpenTTD pull request #8074
Opened 2020-04-10 15:20 UTC by SamuXarick

[PR 8074 test AI.zip](https://github.com/OpenTTD/OpenTTD/files/4462111/PR.8074.test.AI.zip)
[aqueduct scenario.zip](https://github.com/OpenTTD/OpenTTD/files/4462112/aqueduct.scenario.zip)

There are 2 bugs being fixed. I have attached a scenario and an AI that must run with each other.

Bug 1: As an example, tiles 1700 and 1764 are connected, but AreWaterTilesConnected reports that they're not. There are others similar tiles that fall into the same bug.
Bug 2: As an example, tiles 2032 and 2096 aren't connected, but AreWaterTilesConnected reports that they are.

This PR attempts to fix those cases while still maintaining the results the same for the other test cases. I'm sure I didn't handle all the possible cases, but I hope the fixes don't break anything.

2020-04-13 09:49 UTC, SamuXarick commented
Bad connection, due to this bug.
![Green   Co , 2697-07-10](https://user-images.githubusercontent.com/43006711/79111411-66a52a00-7d74-11ea-8bf3-8c24d199e731.png)

2020-04-13 16:50 UTC, frosch123 commented
This bug is missing a root cause analysis.
GetTileTrackStatus() is used by pathfinders, and is very correct.
Replicating the functionality in custom code is prone to errors, in this case I would guess that aqueducts can be entered from below the aqueduct.

The real issue seems to be, that the direction passed to GetTileTrackStatus needs an additional GetReverseDiagDir, since GetTileTrackStatus expects an exitdir, while to_other_tile seems to be an enterdir.

2020-04-13 16:51 UTC, frosch123 requested changes

2020-04-13 16:51 UTC, frosch123 commented on src/script/api/script_marine.cpp
> +	TrackBits gtts1 = ::TrackStatusToTrackBits(::GetTileTrackStatus(t1, TRANSPORT_WATER, 0, INVALID_DIAGDIR)) & ::DiagdirReachesTracks(to_other_tile);
Missing root cause analysis.

2020-04-16 18:30 UTC, frosch123 approved these changes

2020-04-16 18:30 UTC, frosch123 commented
Maybe you also want to check the same for roads and rails.
I am quite sure those methods are also broken, though slightly different.

2020-04-16 18:32 UTC, merged