Trees GUI improvements
OpenTTD/OpenTTD pull request #8234
Opened 2020-06-22 21:17 UTC by nielsmh

Mostly a code change, but has the neat side effect of not drawing more buttons than are tree types in the current climate. Also fixes some scaling margin issues on 2x and 4x GUI scale.
Future proofing for maybe making NewGRF trees one day.

![image](https://user-images.githubusercontent.com/1062071/85336115-6648ae00-b4de-11ea-90b7-06724f7bb65e.png)
![image](https://user-images.githubusercontent.com/1062071/85336128-6a74cb80-b4de-11ea-9b38-beb1e087c23f.png)

2020-06-23 09:18 UTC, nielsmh commented on src/tree_gui.cpp
> +		this->nested_root->AssignSizePosition(ST_RESIZE, 0, 0, this->nested_root->smallest_x, this->nested_root->smallest_y, _current_text_dir == TD_RTL);
I probably need to comment this bit better, about the hacks done to force the window system to calculate sizing for widgets again after calculating a minimum size for the window.

2020-06-23 18:21 UTC, nielsmh commented
Well, I scrapped the NWID_MATRIX based code again, turns out it's really hard to get that to size well, individual buttons actually is easier. Now just generating the buttons instead of having a fixed layout.

2020-06-26 19:58 UTC, nielsmh commented
Now it looks like this:
![image](https://user-images.githubusercontent.com/1062071/85896007-fb59e880-b7f7-11ea-8916-b323dcb3bd07.png)

Planting a "grove" results in something like this:
![image](https://user-images.githubusercontent.com/1062071/85896059-1593c680-b7f8-11ea-9724-cd36f9bbe233.png)

Planting a "forest" results in something like this:
![image](https://user-images.githubusercontent.com/1062071/85896109-293f2d00-b7f8-11ea-88b2-8fb78cb172c5.png)

2020-06-26 20:01 UTC, nielsmh commented on src/tree_cmd.cpp
> +		};
Should I move this function into a common header instead? I'm not sure it's possible to generalise fully.

2020-12-14 22:52 UTC, TrueBrain commented
```
22:49:18 <TrueBrain> nielsm: I really really really like your Trees GUI improvements
22:49:20 <TrueBrain> it looks so cute!
...
22:51:16 *** nielsm has quit IRC (Ping timeout: 480 seconds)
```

:D

2020-12-15 15:39 UTC, TrueBrain commented
Rebased your work and fixed a variable that was unused. Going to test it out now :D

2020-12-15 16:00 UTC, TrueBrain approved these changes
This is really an upgrade :)

The only thing that is now slightly more apparent, the "Random trees" button. You don't expect it to work like that with all the other buttons around.

Not something that needs fixing in this PR, tbh, as it was already weird. It is just now only highlighted more :D

Awesome work!

2020-12-15 16:05 UTC, LordAro commented on src/tree_gui.cpp
> +		}
missing DoPlantForest in this function? Can't click & drag for grove/forest types

2020-12-15 16:05 UTC, TrueBrain requested changes, later dismissed
Awh, testing found a bug .. tooltip say you can drag small and large forest, but you cannot :( I will see if I can discover why not myself too, but if you are interested in solving it, feel welcome :)

2020-12-15 16:18 UTC, 2TallTyler commented
This is very nice. Is there a reason it's restricted to Scenario Editor and we can't have it in-game?

2020-12-26 14:18 UTC, TrueBrain commented
https://user-images.githubusercontent.com/1663690/103153017-90c93b80-478d-11eb-9024-6e37453a25f7.mp4

Rate how awesome this is on a scale from 1 to 10 plz :D

2020-12-26 14:29 UTC, TrueBrain commented
I hope @nielsm doesn't mind, but I hijacked his PR and implemented real dragging of trees; it was easier than trying to figure out how to do selections thingy :D

Let me know what you guys think of this, if it is usable etc :)

2020-12-26 14:31 UTC, TrueBrain commented
> This is very nice. Is there a reason it's restricted to Scenario Editor and we can't have it in-game?

In this implementation it is only possible to do this in the SE, as it would otherwise fire so many `DoCommand`s in MultiPlayer it will effectively DDoS the server :P That is what you get for pretty things :D

2020-12-26 16:39 UTC, LordAro commented
If I open up the tree window in the scenario editor and click once (place trees in a single spot), the cursor changes from a dot to a square.

2020-12-26 19:12 UTC, TrueBrain commented
@LordAro 
> If I open up the tree window in the scenario editor and click once (place trees in a single spot), the cursor changes from a dot to a square.

I cannot reproduce this issue. Do you have a screenshot for me?

2020-12-26 23:58 UTC, LordAro approved these changes
:o

2020-12-27 00:03 UTC, merged