Fix: Add stable economy type that doesn't ruin scenarios with non-standard industry generation
OpenTTD/OpenTTD pull request #8282
Opened 2020-07-28 08:26 UTC by ldpl

OpenTTD production changing and industry closing scheme only supports default evenly-spread random industry generation. Even if scenario does some custom one it will be destroyed as the game goes. And while this issue can be somewhat worked around by using kluge industry sets like "manual industries" it's incompatible with other industry sets (including kluges) and can't be changed if player noticed the issue mid-game. 

Doesn't need a savgame upgrade as it's just a bool->uint8 converssion.

2020-07-28 13:34 UTC, James103 commented
Does this prevent natural industry spawning or is that still controlled by the industry density setting? (I would bet on the latter)

2020-07-28 13:43 UTC, ldpl commented
@James103 Yeah, I'm a fan of having settings as separate as possible so didn't see any reason to interfere with density.

2020-12-14 13:59 UTC, TrueBrain commented
Never been a big fan of having all these different kind of algorithms to do balancing of the game hardcoded in the game. That really should be something for an extension to control, as otherwise you never see the end of this. But I am guessing there is no NewGRF callback for the generic case (only for industries they introduce, I am guessing). I know there are more of these places in our code that are very .. opinionated. Nothing wrong with that, just means there will always be a group of people who would like to see it differently.

I digress. This PR basically only introduces a "do-not-change" mode to industries, if I get this right. The subject is a bit passive aggressive (clearly you are frustrated by something :P), making it a bit hard to see for me if that is the only thing (intended) to be changed here :)

I don't mind a PR like this, but we do need an upper-limit of how many "economies" we want to support. Supporting a "do-not-change" sounds like a sane one to have no matter what.

Two things that come to mind when reviewing:
1) "stable", is that the right word to use here? As x = y + 1 is stable, but not what you mean. Not a native speaker, so just asking the question here :) "Production doesn't change"?
2) "economy.type" somehow ticks me off, not sure why. "type" as variable feels odd. "economy.kind"? Dunno .. thinking out loud here, and splitting hairs.

2020-12-14 19:32 UTC, frosch123 commented
#7912 is about the same, but as GS feature.

2020-12-14 19:49 UTC, andythenorth commented
If I've understood this, it overlaps with requests to newgrf authors like https://www.tt-forums.net/viewtopic.php?p=1239097#p1239097

2020-12-14 20:27 UTC, TrueBrain requested changes

2020-12-14 20:27 UTC, TrueBrain commented on src/lang/english.txt
> +STR_CONFIG_SETTING_ECONOMY_TYPE_HELPTEXT                        :Smooth economy makes production changes more often, and in smaller steps. Stable stops production changes and industry closures. This
`This setting has usually no effect, if industry types are provided by a NewGRF.`
pretty sure the comma is wrong here.
`This setting usually has no effect if industry types are provided by a NewGRF.`

2020-12-14 20:27 UTC, TrueBrain commented on src/lang/english.txt
> +STR_CONFIG_SETTING_ECONOMY_TYPE_STABLE                          :Stable
Stable -> Frozen, is the suggestion on IRC

2020-12-14 20:33 UTC, andythenorth commented
"Fix: Add frozen economy type"

2020-12-14 21:51 UTC, TrueBrain approved these changes

2020-12-14 22:35 UTC, merged