Change: Add some style to GameScript question windows depending on the type
OpenTTD/OpenTTD pull request #8422
Opened 2020-12-23 18:39 UTC by ldpl

## Motivation / Problem

Goal questions have a type parameter but it does nothing but changing the window title. It's impossible for the gamescript to show error that matches the style of openttd own errors.

## Description

PR changes the visual style of GT_ERROR and GT_WARNING messages to make them visually more catchy and, in error case, match the appearance of regular game errors.
![Screenshot from 2020-12-23 21-22-34](https://user-images.githubusercontent.com/413570/103027677-5bdb9f80-4567-11eb-9e9b-cf30ad2b7702.png)

## Limitations
* Couldn't find if the game uses something similar to a warning style already.
* GT_QUESTION and GT_INFO look the same. Couldn't think of a good analogy in default messages.
* Had to make 4 widget layouts since there doesn't seem to be a way to change colors after the declaration and even if it was it won't make it much better as that will make it so window style is basically defined in two places instead of one.
* Had to add colors to language strings, not sure if that's a problem

2020-12-24 14:24 UTC, TrueBrain commented
It really annoys me that the title "center" is not the text "center". Completely unrelated to your PR, I am sure, but boy, that is annoying.

2020-12-24 14:51 UTC, ldpl commented
@TrueBrain yeah, centering is broken on all windows, it's just easier to notice on these. Very annoying but I've no idea how to fix it prooperly.

2020-12-24 15:43 UTC, TrueBrain approved these changes

2020-12-24 15:45 UTC, TrueBrain requested changes

2020-12-24 15:45 UTC, TrueBrain commented on src/goal_gui.cpp
> +	new GoalQuestionWindow(&_goal_question_list_desc[type], id, type == 3 ? TC_WHITE : TC_BLACK, button_mask, question);
given `type` comes in as a byte, would you mind adding an `assert` to ensure it is within the range of the array?

2020-12-24 15:46 UTC, TrueBrain commented on src/goal_gui.cpp
> +	new GoalQuestionWindow(&_goal_question_list_desc[type], id, type == 3 ? TC_WHITE : TC_BLACK, button_mask, question);
In fact, it used to be there:

```
assert(type < GOAL_QUESTION_TYPE_COUNT);
```

but you seem to only have removed it :P :D

2020-12-24 15:51 UTC, TrueBrain approved these changes

2020-12-28 11:27 UTC, LordAro approved these changes

2020-12-28 11:27 UTC, merged