Fix: Prevents crash when no industries are present
OpenTTD/OpenTTD pull request #9726
Opened 2021-12-02 02:36 UTC by Kiptoke

## Motivation / Problem

Resolves #9546:
When industries are removed entirely using the [feature disabler NewGRF](https://bananas.openttd.org/package/newgrf/47572121), a crash occurs when the player opens up the "Fund New Industries" window.

## Description

In the `GetIndustrySpec` function within `industry_cmp.cpp`, changed the assertion statement from `assert(thistype < NUM_INDUSTRYTYPES);`
to `assert(thistype <= NUM_INDUSTRYTYPES);`

This resolves #9546 - now instead of the Fund New Industries window crashing the game, it shows up empty.

## Limitations

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

2021-12-02 03:22 UTC, glx22 commented on src/industry_cmd.cpp
>  	return &_industry_specs[thistype];
But if `thistype` is equal to `NUM_INDUSTRYTYPES` you can cause an invalid read, as `NUM_INDUSTRYTYPES` is out of the array bounds.

2021-12-07 08:12 UTC, nielsmh commented on src/industry_gui.cpp
> +		if (count == 0) return;
```suggestion
		if (this->count == 0) return;
```
Code style guidelines prescribe that class members must always be qualified,

2022-01-05 12:17 UTC, LordAro requested changes
You seem to have changed file modes to 100644 -> 100755 as well - please revert this change

(If you're on Windows, this can be tricky - see http://blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html (but use `-x` instead of `+x` )

2022-01-05 12:17 UTC, LordAro commented on src/industry_gui.cpp
> +						SetDParam(0, (_settings_game.construction.raw_industry_construction == 2 && false) ? STR_FUND_INDUSTRY_PROSPECT_NEW_INDUSTRY : STR_FUND_INDUSTRY_FUND_NEW_INDUSTRY);
`&& false` ?

I think we can remove some code here

2022-01-05 12:17 UTC, LordAro commented on src/industry_gui.cpp
> +						SetDParam(0, (_settings_game.construction.raw_industry_construction == 2 && false) ? STR_FUND_INDUSTRY_PROSPECT_NEW_INDUSTRY : STR_FUND_INDUSTRY_FUND_NEW_INDUSTRY);
`&& false` ?

I think we can remove some code here

2022-02-04 20:22 UTC, rubidium42 submitted a review, later dismissed

2022-04-30 09:53 UTC, LordAro approved these changes

2022-04-30 17:29 UTC, merged