Fix some mistaken Romanian real towns
OpenTTD/OpenTTD pull request #9819
Opened 2022-02-18 14:32 UTC by ALEX11BR

Galași -> Galați
Brațov -> Brașov
Băilesti -> Băilești
Călărasi -> Călărași
Drăgăsani -> Drăgășani
Făgăras -> Făgăraș
Târgoviste -> Târgoviște
Târgu Mures ->Târgu Mureș
Tăndărei -> Țăndărei

## Motivation / Problem

## Description

## Limitations

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

2022-02-21 07:36 UTC, nielsmh requested changes, later dismissed

2022-02-21 07:36 UTC, nielsmh commented on src/table/townname.h
> +	u8"\u021a\u0103nd\u0103rei",
You should not change the order of the names, even if that will make them sorted wrong in the list. If you change the order, existing saved games will suddenly have towns change name and confuse the player.

2022-02-22 18:59 UTC, nielsmh reviewed
The commit checker complains about your commit message, you can't have non-ASCII characters in it.
The actual change looks fine to me now.

2022-03-20 17:51 UTC, LordAro approved these changes
Assuming there's no issues with sprite fonts and things, by all means

2022-03-26 08:08 UTC, nielsmh commented
I tested all the new names in-game with both original graphics and OpenGFX sprite fonts, and didn't notice any issues with the characters used.

2022-03-26 08:08 UTC, merged